export const ADJECTIVES = [
    "Wacky",
    "Goofy",
    "Zany",
    "Silly",
    "Clumsy",
    "Snazzy",
    "Funky",
    "Quirky",
    "Nifty",
    "Loopy",
    "Bouncy",
    "Chunky",
    "Bizarre",
    "Dorky",
    "Spunky",
    "Whimsical",
    "Nutty",
    "Zesty",
    "Grumpy",
    "Cheeky",
    "Jolly",
    "Perky",
    "Cranky",
    "Fluffy",
    "Wobbly",
    "Spicy",
    "Weird",
    "Cuddly",
    "Quacky",
    "Giggly"
];

export const MOVIES = [
    "The $ King",
    "Jurassic $",
    "Star $",
    "The Dark $",
    "The $father",
    "Harry $",
    "Finding $",
    "Forrest $",
    "The $",
    "Pirates of the $",
    "The Hunger $",
    "Spider-$",
    "Black $",
    "$",
    "Beauty and the $",
    "The $",
    "The $",
    "The Lord of the $",
    "$",
    "Mad $"
];
;

export const VOWELSUFFIXES = [
    "-zzy", 
    "-roo", 
    "-pie", 
    "-boo", 
    "-licious", 
    "-topia", 
    "-loo", 
    "-nado", 
    "-yo", 
    "-fy", 
    "-ny"
];

export const CONSONANTSUFFIXES = [
    "-inator", 
    "-zilla", 
    "-tron", 
    "-saurus", 
    "-burger", 
    "-master", 
    "-bot", 
    "-pants", 
    "-mobile", 
    "-head", 
    "-worth", 
    "-doodle", 
    "-pocalypse", 
    "-fizz", 
    "-whiz"
];

export const PREFIXES = [
    "Super", 
    "Mega", 
    "Ultra", 
    "Hyper", 
    "Captain", 
    "Doctor", 
    "Professor", 
    "Mighty", 
    "King", 
    "Queen", 
    "Sir", 
    "Lady", 
    "Master", 
    "Shadow", 
    "Agent", 
    "Lord", 
    "Grand", 
    "Big", 
    "Lil", 
    "Sneaky", 
    "Fluffy", 
    "Bouncy", 
    "Turbo", 
    "Iron", 
    "Crazy", 
    "Wacky", 
    "Epic", 
    "Mystic", 
    "Stealthy", 
    "Magic"
];

export const VOWELS = ['a', 'e', 'i', 'o', 'u'];
